### PR TITLE
Fixes the path to the commonjs-usable format. Fixes #133

### LINKED ISSUE #133: Fix package.json for use with npm + Browserify
The package,json doesn't actually point to a file that exists and can be used with Browserify.

It would be nice to have a `quo.node.js` that is a min/merged output that will set `module.exports = $$` so that it can be used with Browserify.  Then you'd need to update your main/start script in the package.json and publish to npm.

### PR DESCRIPTION
**Pull request by mike-engel**
Should fix #133 according to my brief testing.

### CODE REVIEW

**Comment by holic** [comment]
:+1:

**Comment by mike-engel** [comment]
Since I kind of need this to be in sooner rather than later, if this isn't merged soon, I'll probably publish a `quojs-standalone` package until this gets merged in.

**Comment by soyjavi** [comment]
Merged!! :)

**Comment by mike-engel** [comment]
Awesome, thanks @soyjavi!

**Comment by holic** [comment]
Thanks guys!

**Comment by mike-engel** [comment]
Er, @soyjavi I must have edited the wrong package.json becuase the `main` attribute in the published package.json is still incorrect. Should be https://github.com/soyjavi/QuoJS/blob/master/package.json#L11

**Comment by holic** [comment]
Maybe he hasn't published it to npm yet? In the meantime, you can require the module straight from GitHub: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by mike-engel** [comment]
Looks like you're right @holic. Using the github method doesn't work because the coffeescript version of package.json in here isn't readable by npm. @soyjavi Can you publish a 3.0.9 with this change when you get a chance?

**Pull request merged**
